"""Add Threat Intel

Revision ID: 235355272130
Revises: 0fe815adcd9e
Create Date: 2025-03-23 13:23:43.168347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235355272130'
down_revision = '0fe815adcd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=200), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threat_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_intelligence')
    # ### end Alembic commands ###
