"""empty message

Revision ID: 355005ce1134
Revises: 9adcf0bb35dd
Create Date: 2025-03-18 13:19:04.373467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355005ce1134'
down_revision = '9adcf0bb35dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_reports', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
