"""Initial Migration

Revision ID: d212bba1e5a2
Revises: 
Create Date: 2025-01-22 22:23:03.321357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd212bba1e5a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('iocs', sa.Text(), nullable=True),
    sa.Column('affected_platforms', sa.Text(), nullable=True),
    sa.Column('affected_platform_ver', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=False),
    sa.Column('impact_type', sa.String(length=50), nullable=True),
    sa.Column('severity_level', sa.String(length=50), nullable=True),
    sa.Column('mitigation_actions', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=False),
    sa.Column('os_name', sa.String(length=100), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=True),
    sa.Column('service_version', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('salutation', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('team', sa.String(length=120), nullable=True),
    sa.Column('domain', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('assets')
    op.drop_table('threat_reports')
    op.drop_table('organizations')
    # ### end Alembic commands ###
